// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unipsico.Data;

#nullable disable

namespace Unipsico.Migrations
{
    [DbContext(typeof(ApllicationDb))]
    partial class ApllicationDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Unipsico.Models.AlunoModel", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("IdadeAluno")
                        .HasColumnType("int");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RaAluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SalaAluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AlunoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Unipsico.Models.ConsultaModel", b =>
                {
                    b.Property<Guid>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("char(36)");

                    b.HasKey("ConsultaId");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Unipsico.Models.EnderecoModel", b =>
                {
                    b.Property<Guid>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EnderecoId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Unipsico.Models.EstagioModel", b =>
                {
                    b.Property<Guid>("EstagioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataEstagio")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("InstituicaoCredenciadaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("char(36)");

                    b.HasKey("EstagioId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("InstituicaoCredenciadaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Estagios");
                });

            modelBuilder.Entity("Unipsico.Models.InstituicaoCredenciadaModel", b =>
                {
                    b.Property<Guid>("InstituicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NomeInstituicao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("InstituicaoId");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("InstituicoesCredenciadas");
                });

            modelBuilder.Entity("Unipsico.Models.PacienteModel", b =>
                {
                    b.Property<Guid>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CelularPaciente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CpfPaciente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailPaciente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdadePaciente")
                        .HasColumnType("int");

                    b.Property<string>("NomePaciente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PacienteId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Unipsico.Models.ProfessorModel", b =>
                {
                    b.Property<Guid>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("NomeProfessor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProfessorId");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("Unipsico.Models.ConsultaModel", b =>
                {
                    b.HasOne("Unipsico.Models.AlunoModel", "Aluno")
                        .WithOne("Consulta")
                        .HasForeignKey("Unipsico.Models.ConsultaModel", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unipsico.Models.PacienteModel", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unipsico.Models.ProfessorModel", "Professor")
                        .WithMany("Consulta")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Paciente");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Unipsico.Models.EstagioModel", b =>
                {
                    b.HasOne("Unipsico.Models.AlunoModel", "Aluno")
                        .WithMany("Estagio")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unipsico.Models.InstituicaoCredenciadaModel", "InstituicaoCredenciada")
                        .WithMany("Estagios")
                        .HasForeignKey("InstituicaoCredenciadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unipsico.Models.ProfessorModel", "Professor")
                        .WithMany("Estagio")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("InstituicaoCredenciada");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Unipsico.Models.InstituicaoCredenciadaModel", b =>
                {
                    b.HasOne("Unipsico.Models.EnderecoModel", "Endereco")
                        .WithOne("InstituicaoCredenciada")
                        .HasForeignKey("Unipsico.Models.InstituicaoCredenciadaModel", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Unipsico.Models.AlunoModel", b =>
                {
                    b.Navigation("Consulta")
                        .IsRequired();

                    b.Navigation("Estagio");
                });

            modelBuilder.Entity("Unipsico.Models.EnderecoModel", b =>
                {
                    b.Navigation("InstituicaoCredenciada");
                });

            modelBuilder.Entity("Unipsico.Models.InstituicaoCredenciadaModel", b =>
                {
                    b.Navigation("Estagios");
                });

            modelBuilder.Entity("Unipsico.Models.PacienteModel", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("Unipsico.Models.ProfessorModel", b =>
                {
                    b.Navigation("Consulta");

                    b.Navigation("Estagio");
                });
#pragma warning restore 612, 618
        }
    }
}
